spring:
  application:
    name: hr-service

  r2dbc:
    username: hr_user
    password: ${hr_DB_PASSWORD:hr_pwd}
    properties:
      schema: hr_schema
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/emis_db?schema=hr_schema
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10

  flyway:
    user: hr_user
    password: ${FLYWAY_DB_PASSWORD:hr_pwd}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/emis_db
    default-schema: hr_schema
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  cloud:
    stream:
      defaultBinder: kafka
      bindings:
        staffAssignment-out-0:
          destination: hr.staff.assignment.v1
          content-type: application/json
          producer:
            error-channel-enabled: true

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        bindings:
          staffAssignment-out-0:
            producer:
              configuration:
                acks: all
                enable-idempotence: true
                retries: 5
                max.in-flight.requests.per.connection: 5



#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/emis
#  lifecycle:
#    timeout-per-shutdown-phase: 15s


server:
  port: 8085
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

#springdoc:
#  swagger-ui:
#    path: /swagger-ui

# application-prod.yml
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.reactive.result.method.annotation: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    org.flywaydb: DEBUG


emis:
  services:
    school-service-properties:
      base-url: ${EMIS_SERVICE_URL:http://localhost:8082}
      get-school-details-url: ${emis.services.school-service-properties.base-url}/api/v1/schools/{schoolCode}

    academic-service-properties:
      base-url: ${EMIS_SERVICE_URL:http://localhost:8084}
      get-class-section-url: ${emis.services.academic-service-properties.base-url}/api/v1/academic/schools/{schoolCode}/classes/{classId}/sections/{sectionId}

    timeout: 5

